name: CI

on:
  push:
    branches:
      - main
      - feat/#6_CICD
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.2-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.4

    - name: Build
      run: go build -v ./...

    - name: Test
      env:
        TRANSACTION_POOL_DB_HOST: localhost
        TRANSACTION_POOL_DB_PORT: 5432
        TRANSACTION_POOL_DB_USERNAME: postgres
        TRANSACTION_POOL_DB_PASSWORD: postgres
        TRANSACTION_POOL_DB_NAME: postgres
      run: go test -v ./...
      