name: Go

on:
  push:
    branches:
      - main
      - feat/#6_CICD
  pull_request:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.4

    - name: Build
      run: go build -v ./...

    - name: Test
      run: |
        ./scripts/run_database.sh
        ./scripts/run_tests.sh
