name: CI

on:
  push:
    branches:
      - feat/#6_CICD
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: show env
        run: env
      - name: Preparation
        id: prep
        run: |
          IMAGE="${{ github.repository }}"
          TAGS="${IMAGE}:${{ github.sha }}"
          if [[ $GITHUB_REF == ref/head/master ]]; then
            TAGS="${TAGS},${IMAGE}:latest"
          fi
          echo ::set-output name=tags::${TAGS}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.prep.outputs.tags }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}